### ISSUE TITLE
没怎么看明白，来个完整的示例如何？group by 呢？

### ISSUE THREAD

**Issue by tms2003** [liyanjie8712/Jsonql#1]

**Comment by liyanjie8712** [comment]
不好意思没有提供在线的测试地址。src目录内已提供了两个简单的Demo项目，分别是AspNet与AspNetCore，相关依赖项可以去http://myget.org/gallery/liyanjie下载，Demo跑起来会有一个test工具，可以实际编写查询测试一下。
